"""Initial migration

Revision ID: 944c0745cc34
Revises: 
Create Date: 2025-12-16 00:11:57.973209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '944c0745cc34'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('distance', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(), nullable=True))
    op.add_column('users', sa.Column('about', sa.String(), nullable=True))
    op.add_column('users', sa.Column('images_url', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'images_url')
    op.drop_column('users', 'about')
    op.drop_column('users', 'location')
    op.drop_column('users', 'distance')
    # ### end Alembic commands ###
